version: "3.8"

services:
  eder-barrios-cv:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eder-barrios-portfolio
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge
